<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE hibernate-mapping PUBLIC "-//Hibernate/Hibernate Mapping DTD 3.0//EN"
"http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd">
<!-- 
    Mapping file autogenerated by MyEclipse Persistence Tools
-->

<hibernate-mapping>
    <class name="${objs.pagckdir}.${objs.className}" table="${objs.tableName}" catalog="${objs.dataBase}">
<#list polist as o>
    <#if o.isPk == 'true'>
	    <id name="${o.fname}" type="${o.ftype}">
            <column name="${o.columnName}" length="${o.columnLength}" />
            <generator class="${o.key_set}"></generator>
        </id>
	</#if>
</#list>
<#list polist as o>
    <#if o.isPk == 'false'>
	   <#if o.columnLengthIn == ''>
	    <property name="${o.fname}" type="${o.ftype}">
	        <column name="${o.columnName}" <#if o.columnLength != ''>length="${o.columnLength}" </#if> />
	    </property>
	   <#else>
	    <property name="${o.fname}" type="${o.ftype}">
	        <column name="${o.fname}" precision="${o.columnLength}" scale="${o.columnLengthIn}" />
	    </property>
	   </#if>
    </#if>
</#list>
    </class>
</hibernate-mapping>
