/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-04-17 08:40:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>正式版本</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"initial-scale=1,width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no\">\r\n");
      out.write("   \t<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("    <meta content=\"yes\" name=\"apple-touch-fullscreen\">\r\n");
      out.write("   \t<meta name=\"App-Config\" content=\"fullscreen=yes,useHistoryState=yes,transition=yes\">\r\n");
      out.write("   \t<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("    <meta name=\"format-detection\" content=\"telephone=no,email=no\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/demo.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/microdone-h5.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/demo.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/microdone-h5.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar kb = new keyBoard({\r\n");
      out.write("\t\t\t\"chaosMode\" : 1,// 混乱模式,0:无混乱;1:打开时乱一次;2:每输入一个字符乱一次,默认值0\r\n");
      out.write("\t\t\t\"pressStatus\" :1,// 按键状态,0:按下、抬起按键无变化;1:按下后有放大镜效果;2:按下、抬起按键的颜色变化,默认值0\r\n");
      out.write("\t\t\t\"kbType\" : 0,// 键盘类型,0:全键盘;1:纯数字键盘,默认值0\r\n");
      out.write("\t\t\t\"svg\":\"svg\"//svg图片的地址\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar passGuard1 = new passGuard({\r\n");
      out.write("\t\t\t\"mappurl\" : \"./send_mapping.jsp\",\r\n");
      out.write("\t\t\t\"maxLength\" : 12,// 最大输入长度\r\n");
      out.write("\t\t\t\"regExp1\" : \"[\\\\S\\\\s]\",// 输入过程限制的正则\r\n");
      out.write("\t\t\t\"regExp2\": \"[0-9]{6,12}\",\r\n");
      out.write("\t\t\t\"displayMode\" : 0,// 显示形式,0:星号;1:明文,默认值0\r\n");
      out.write("\t\t\t\"callBack\":cb1,//成功回调\r\n");
      out.write("\t    \t\"errorCallBack\":cb2,//失败回调\r\n");
      out.write("\t\t\t\"rsaPublicKey\" : \"3081890281810092d9d8d04fb5f8ef9b8374f21690fd46fdbf49b40eeccdf416b4e2ac2044b0cfe3bd67eb4416b26fd18c9d3833770a526fd1ab66a83ed969af74238d6c900403fc498154ec74eaf420e7338675cad7f19332b4a56be4ff946b662a3c2d217efbe4dc646fb742b8c62bfe8e25fd5dc59e7540695fa8b9cd5bfd9f92dfad009d230203010001\"// rsa公钥\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar passGuard2 = new passGuard({\r\n");
      out.write("\t\t\t\"mappurl\" : \"./send_mapping.jsp\",\r\n");
      out.write("\t\t\t\"maxLength\" : 12,// 最大输入长度\r\n");
      out.write("\t\t\t\"regExp1\" : \"[\\\\S\\\\s]\",// 输入过程限制的正则\r\n");
      out.write("\t\t\t\"regExp2\": \"[a-z]{6,12}\",\r\n");
      out.write("\t\t\t\"displayMode\" : 0,// 显示形式,0:星号;1:明文,默认值0\r\n");
      out.write("\t\t\t\"callBack\":cb3,//成功回调\r\n");
      out.write("\t    \t\"errorCallBack\":cb4,//失败回调\r\n");
      out.write("\t\t\t\"rsaPublicKey\" : \"3081890281810092d9d8d04fb5f8ef9b8374f21690fd46fdbf49b40eeccdf416b4e2ac2044b0cfe3bd67eb4416b26fd18c9d3833770a526fd1ab66a83ed969af74238d6c900403fc498154ec74eaf420e7338675cad7f19332b4a56be4ff946b662a3c2d217efbe4dc646fb742b8c62bfe8e25fd5dc59e7540695fa8b9cd5bfd9f92dfad009d230203010001\"// rsa公钥\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar passGuard3 = new passGuard({\r\n");
      out.write("\t\t\t\"mappurl\" : \"./send_mapping.jsp\",\r\n");
      out.write("\t\t\t\"maxLength\" : 12,// 最大输入长度\r\n");
      out.write("\t\t\t\"regExp1\" : \"[\\\\S\\\\s]\",// 输入过程限制的正则\r\n");
      out.write("\t\t\t\"regExp2\": \"[0-9]{6,12}\",\r\n");
      out.write("\t\t\t\"displayMode\" : 0,// 显示形式,0:星号;1:明文,默认值0\r\n");
      out.write("\t\t\t\"callBack\":cb5,//成功回调\r\n");
      out.write("\t    \t\"errorCallBack\":cb6,//失败回调\r\n");
      out.write("\t\t\t\"rsaPublicKey\" : \"3081890281810092d9d8d04fb5f8ef9b8374f21690fd46fdbf49b40eeccdf416b4e2ac2044b0cfe3bd67eb4416b26fd18c9d3833770a526fd1ab66a83ed969af74238d6c900403fc498154ec74eaf420e7338675cad7f19332b4a56be4ff946b662a3c2d217efbe4dc646fb742b8c62bfe8e25fd5dc59e7540695fa8b9cd5bfd9f92dfad009d230203010001\"// rsa公钥\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction cb1(){\r\n");
      out.write("\t\t\tconsole.log(\"成功1\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cb2(){\r\n");
      out.write("\t\t\tconsole.log(\"失败1\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cb3(){\r\n");
      out.write("\t\t\tconsole.log(\"成功2\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cb4(){\r\n");
      out.write("\t\t\tconsole.log(\"失败2\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cb5(){\r\n");
      out.write("\t\t\tconsole.log(\"成功3\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cb6(){\r\n");
      out.write("\t\t\tconsole.log(\"失败3\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \t <form id=\"form1\" name=\"form1\" method=\"post\" action=\"decrypt.jsp\"\">\r\n");
      out.write("    <div id=\"Main\">\r\n");
      out.write("        <div id=\"TitleBar\">\r\n");
      out.write("            <div id=\"LogoBg_Topbar\">\r\n");
      out.write("                \t北京微通新成手机网银密码控件Demo\r\n");
      out.write("            </div>\r\n");
      out.write("             <div id=\"LoginTab\">\r\n");
      out.write("                <table id=\"TabTitle\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"left on\">\r\n");
      out.write("                                        登录场景\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>           \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"InputBlock\">\r\n");
      out.write("            <div id=\"InputInfoTable\">\r\n");
      out.write("                <div class=\"line5px\" ></div>\r\n");
      out.write("                <table class=\"InputLine\">\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"left\" align=\"right\">\r\n");
      out.write("                                <table class=\"AutoAlignLabel\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"BeginWord\">账</td>\r\n");
      out.write("                                        <td class=\"EndWord\">号</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"right\" align=\"left\">\r\n");
      out.write("  <input type=\"text\" value=\"tester\" id=\"username\" onfocus=\"kb.hide();\" name=\"username\" class=\"de2 NoneInput90\" maxlength=\"50\" tabindex=\"1\"/>\r\n");
      out.write("                            <input type=\"text\" value=\"tester\" id=\"username2\" onfocus=\"kb.hide();\" name=\"username\" class=\"de2 NoneInput90\" maxlength=\"50\" tabindex=\"1\"/>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"line0px\"></div>\r\n");
      out.write("                <table class=\"InputLine\">\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"left\" align=\"right\">\r\n");
      out.write("                                <table class=\"AutoAlignLabel\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"BeginWord\">登</td>\r\n");
      out.write("                                        <td class=\"MidWord\">录</td>\r\n");
      out.write("                                        <td class=\"MidWord\">密</td>\r\n");
      out.write("                                        <td class=\"EndWord\">码</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"right\" align=\"left\" >\r\n");
      out.write("                                <input type=\"text\" readonly=\"readonly\" id=\"kb1\" name=\"input3\" placeholder=\"请输入密码\" class=\"default NoneInput90\" maxlength=\"50\" tabindex=\"3\" \"/>\r\n");
      out.write("                            <script>\r\n");
      out.write("\t\t\t  \t\t\t\t\t//初始化密码卫士,绑定键盘对象。数字参数：0代表全键盘，1代表数字键盘\r\n");
      out.write("\t\t\t  \t\t\t\t\tpassGuard1.generate(\"kb1\",kb,1);\r\n");
      out.write("\t\t  \t\t\t\t\t</script>\r\n");
      out.write("\t  \t\t\t\t</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                      <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"left\" align=\"right\">\r\n");
      out.write("                                <table class=\"AutoAlignLabel\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"BeginWord\">登</td>\r\n");
      out.write("                                        <td class=\"MidWord\">录</td>\r\n");
      out.write("                                        <td class=\"MidWord\">密</td>\r\n");
      out.write("                                        <td class=\"EndWord\">码</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"right\" align=\"left\">\r\n");
      out.write("                                <input type=\"text\" id=\"kb2\" readonly=\"readonly\" name=\"input3\" placeholder=\"请输入姓名\" class=\"default NoneInput90\" maxlength=\"50\" tabindex=\"3\"/>\r\n");
      out.write("                            <script>\r\n");
      out.write("\t\t\t  \t\t\t\t\t//初始化密码卫士,绑定键盘对象。数字参数：0代表全键盘，1代表数字键盘\r\n");
      out.write("\t\t\t  \t\t\t\t\tpassGuard2.generate(\"kb2\",kb,0);\r\n");
      out.write("\t\t  \t\t\t\t\t</script>\r\n");
      out.write("\t  \t\t\t\t</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"left\" align=\"right\">\r\n");
      out.write("                                <table class=\"AutoAlignLabel\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"BeginWord\">登</td>\r\n");
      out.write("                                        <td class=\"MidWord\">录</td>\r\n");
      out.write("                                        <td class=\"MidWord\">密</td>\r\n");
      out.write("                                        <td class=\"EndWord\">码</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"right\" align=\"left\" >\r\n");
      out.write("                                <input type=\"text\" readonly=\"readonly\" id=\"kb3\" name=\"input3\" placeholder=\"请输入密码\" class=\"default NoneInput90\" maxlength=\"50\" tabindex=\"3\"/>\r\n");
      out.write("                            <script>\r\n");
      out.write("\t\t\t  \t\t\t\t\t//初始化密码卫士,绑定键盘对象。数字参数：0代表全键盘，1代表数字键盘\r\n");
      out.write("\t\t\t  \t\t\t\t\tpassGuard3.generate(\"kb3\",kb,0);\r\n");
      out.write("\t\t  \t\t\t\t\t</script>\r\n");
      out.write("\t  \t\t\t\t</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"line0px\"></div>\r\n");
      out.write("                <div class=\"line0px\"></div>\r\n");
      out.write("                <div class=\"line10px\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"LoginBar\">\r\n");
      out.write("            \t<table id=\"LoginBtn\" onclick=\"javascript:formSubmit();\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            登录\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"username\" id=\"username\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"password\" id=\"password\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"repassword\" id=\"repassword\" value=\"\"/>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t//var Le;\r\n");
      out.write("\t\twindow.onload=function(){\r\n");
      out.write("\t\t\tLe = $(\".default\").length;\r\n");
      out.write("\t\t\tkb.generate();\r\n");
      out.write("\t\t\twinHeight = $(window).height();\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
