package com.spz.tools.hibernate.entity;
// Generated 2019-1-17 14:55:37 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="myschool"
)
public class Subject  implements java.io.Serializable {


     private Integer subjectNo;
     private Grade grade;
     private String subjectName;
     private Integer classHour;
     private Set results = new HashSet(0);
     private Set results_1 = new HashSet(0);

    public Subject() {
    }

    public Subject(Grade grade, String subjectName, Integer classHour, Set results, Set results_1) {
       this.grade = grade;
       this.subjectName = subjectName;
       this.classHour = classHour;
       this.results = results;
       this.results_1 = results_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="subjectNo", unique=true, nullable=false)
    public Integer getSubjectNo() {
        return this.subjectNo;
    }
    
    public void setSubjectNo(Integer subjectNo) {
        this.subjectNo = subjectNo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gradeId")
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }
    
    @Column(name="subjectName", length=50)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    
    @Column(name="classHour")
    public Integer getClassHour() {
        return this.classHour;
    }
    
    public void setClassHour(Integer classHour) {
        this.classHour = classHour;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="subject")
    public Set getResults() {
        return this.results;
    }
    
    public void setResults(Set results) {
        this.results = results;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="subject")
    public Set getResults_1() {
        return this.results_1;
    }
    
    public void setResults_1(Set results_1) {
        this.results_1 = results_1;
    }




}


