package com.spz.tools.hibernate.entity;
// Generated 2019-1-17 14:55:37 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="myschool"
)
public class Teacher  implements java.io.Serializable {


     private Integer teacherId;
     private String teacherName;
     private int age;
     private int teacherYear;
     private int gradeId;
     private Set students = new HashSet(0);
     private Set students_1 = new HashSet(0);

    public Teacher() {
    }

	
    public Teacher(String teacherName, int age, int teacherYear, int gradeId) {
        this.teacherName = teacherName;
        this.age = age;
        this.teacherYear = teacherYear;
        this.gradeId = gradeId;
    }
    public Teacher(String teacherName, int age, int teacherYear, int gradeId, Set students, Set students_1) {
       this.teacherName = teacherName;
       this.age = age;
       this.teacherYear = teacherYear;
       this.gradeId = gradeId;
       this.students = students;
       this.students_1 = students_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="teacherId", unique=true, nullable=false)
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
    
    @Column(name="teacherName", nullable=false, length=50)
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    
    @Column(name="age", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    
    @Column(name="teacherYear", nullable=false)
    public int getTeacherYear() {
        return this.teacherYear;
    }
    
    public void setTeacherYear(int teacherYear) {
        this.teacherYear = teacherYear;
    }
    
    @Column(name="gradeId", nullable=false)
    public int getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(int gradeId) {
        this.gradeId = gradeId;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="relation_ts", catalog="myschool", joinColumns = { 
        @JoinColumn(name="teacherId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="studentNo", nullable=false, updatable=false) })
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="relation_ts", catalog="myschool", joinColumns = { 
        @JoinColumn(name="teacherId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="studentNo", nullable=false, updatable=false) })
    public Set getStudents_1() {
        return this.students_1;
    }
    
    public void setStudents_1(Set students_1) {
        this.students_1 = students_1;
    }




}


